name: Playwright Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      # Checkout code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright browser
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      # Upload HTML report
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Upload test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 30

      # Generate Allure Report
      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@v1.9
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      # Upload Allure Report as Artifact
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-history/
          retention-days: 30